### ISSUE TITLE
IPO PyPi account

### ISSUE THREAD

**Issue by lewisjared** [CMIP-REF/cmip-ref#12]
## The problem
I would like to publish the core package to pypi in the coming days. Is there an IPO account I could add as a collaborator in the unfortunate event that I get hit by a bus. @eleanororourke @wolfiex

## Definition of "done"
* [ ] IPO collaborators identified
* [ ] Registered with PyPi

**Comment by wolfiex** [comment]
Hey Jared, 

There is a  WCRP-CMIP (https://github.com/WCRP-CMIP)  organisation that most of the public facing scripts and libraries are situated.  It is usually a good idea to have these together so that new and existing users only have one place to search. 

As for your question - the account is [@cmip-ipo](https://github.com/CMIP-IPO)


Hope that clarifies your question and best of luck in your bus-avoiding endeavours :P 

Dan

**Comment by lewisjared** [comment]
Thanks for the info. I've tried to invite @cmip-ipo a few times now and the invitation has timed out both times. Perhaps the invite goes to an unmonitored email?

There will be a range of repositories that are all linked together so I thought it would be better to keep them together under one GH organisation. We can figure out the final resting place of these repos once we are ready to launch.

**Comment by CMIP-IPO** [comment]
Can you do it again, I thought Dan was picking up as he was the one that wanted the IPO account invited and uses it.

Please send it again and I will look in our manual log in and accept. Thanks Jared

Briony
________________________________

**Comment by lewisjared** [comment]
Done you should have an invite waiting for you.

**Comment by lewisjared** [comment]
I see that @CMIP-IPO is now a member of the org!
